Repository paradedb/paradedb, pull requests merged in 2025-08, with the labels that each got.

#2927 fix: relation extension cache invalidation
  pg_search/Cargo.toml
  pg_search/src/index/writer/segment_component.rs
  pg_search/src/postgres/storage/buffer.rs
  pg_search/src/postgres/storage/linked_bytes.rs
  pg_search/src/postgres/storage/metadata.rs
  pg_search/src/postgres/storage/utils.rs
Labels: benchmark-stressgres, benchmark-benchmarks

#2970 feat: support aggregation over JSON data in aggregate custom scan.
  pg_search/src/postgres/customscan/aggregatescan/mod.rs
  pg_search/tests/pg_regress/expected/json_aggregate.out
  pg_search/tests/pg_regress/expected/json_groupby_aggregate.out
  pg_search/tests/pg_regress/sql/json_aggregate.sql
  pg_search/tests/pg_regress/sql/json_groupby_aggregate.sql
Labels: cherry-pick/0.18.x

#3020 fix: restore the garbage list
  pg_search/src/index/directory/utils.rs
  pg_search/src/postgres/storage/metadata.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3023 fix: Only mark Docker images as `latest` if they actually are the latest ones
  .github/workflows/publish-paradedb-docker.yml
  .github/workflows/test-pg_search-docker.yml
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3031 perf: optimize merging heuristics to prefer background merging
  pg_search/src/postgres/merge.rs
  pg_search/src/postgres/storage/merge.rs
  tests/tests/layered_merge.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3037 fix: make IndexLayerSizes calculations more accurate
  pg_search/src/postgres/merge.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3039 fix: make IndexLayerSizes calculations more accurate
  pg_search/src/postgres/merge.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3019 fix: Remove the string/numeric classification from fast fields explain
  Cargo.lock
  docs/documentation/aggregates/overview.mdx
  pg_search/Cargo.toml
  pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs
  pg_search/tests/pg_regress/expected/aggregate.out
  pg_search/tests/pg_regress/expected/custom_scan_is_numeric_fast_field_capable.out
  pg_search/tests/pg_regress/expected/groupby_aggregate.out
  pg_search/tests/pg_regress/expected/issue_2932.out
  pg_search/tests/pg_regress/expected/mixed_fast_fields_bug.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_01_aggregation.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_02_mixed_fast_non_fast.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_04_execution_method_selection.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_05_union_window_functions.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_06_score_function.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_07_recursive_cte.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_08_type_conversion.out
  pg_search/tests/pg_regress/expected/mixedff_advanced_09_multi_index_search.out
  pg_search/tests/pg_regress/expected/mixedff_basic_01_basic_mixed_fields.out
  pg_search/tests/pg_regress/expected/mixedff_basic_02_multiple_string_fields.out
  pg_search/tests/pg_regress/expected/mixedff_basic_03_multiple_numeric_fields.out
  pg_search/tests/pg_regress/expected/mixedff_basic_04_mixed_field_types.out
  pg_search/tests/pg_regress/expected/mixedff_basic_05_uuid.out
  pg_search/tests/pg_regress/expected/mixedff_edgecases_01_corner_cases.out
  pg_search/tests/pg_regress/expected/mixedff_edgecases_02_null_handling.out
  pg_search/tests/pg_regress/expected/mixedff_edgecases_03_string_edge_cases.out
  pg_search/tests/pg_regress/expected/mixedff_edgecases_04_complex_string_patterns.out
  pg_search/tests/pg_regress/expected/mixedff_edgecases_05_numeric_handling.out
  pg_search/tests/pg_regress/expected/mixedff_queries_01_complex_join.out
  pg_search/tests/pg_regress/expected/mixedff_queries_02_order_by.out
  pg_search/tests/pg_regress/expected/mixedff_queries_03_cte_test.out
  pg_search/tests/pg_regress/expected/mixedff_queries_05_join2.out
  tests/tests/fast_fields.rs
Labels: cherry-pick/0.18.x

#3048 ci: Fix out-of-order benchmark workflow steps and broken Slack alerts
  .github/actions/benchmark-benchmarks/action.yml
  .github/actions/benchmark-stressgres/action.yml
  .github/workflows/benchmark-backfill-auto.yml
  .github/workflows/benchmark-pg_search-benchmarks.yml
  .github/workflows/benchmark-pg_search-stressgres.yml
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3061 fix: cleanup fsm overhead and fix `content.header.empty` bug
  pg_search/src/postgres/storage/fsm.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3046 feat: heap filter pushdown works with sub-queries
  pg_search/src/index/reader/index.rs
  pg_search/src/postgres/customscan/mod.rs
  pg_search/src/postgres/customscan/pdbscan/mod.rs
  pg_search/src/postgres/customscan/pdbscan/scan_state.rs
  pg_search/src/postgres/customscan/pdbscan/solve_expr.rs
  pg_search/src/postgres/customscan/qual_inspect.rs
  pg_search/src/query/heap_field_filter.rs
  pg_search/src/query/iter_mut.rs
  pg_search/src/query/mod.rs
  pg_search/tests/pg_regress/expected/unified_expression_comprehensive.out
  pg_search/tests/pg_regress/sql/unified_expression_comprehensive.sql
Labels: cherry-pick/0.18.x

#3073 fix: don't include target_segment_count in background_layer_sizes
  pg_search/src/postgres/merge.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3078 fix: teach `push-file.yaml` how to retry
  .github/actions/push-file/action.yml
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3083 perf: FSM conditional locking & other minor drive-bys
  pg_search/src/index/directory/utils.rs
  pg_search/src/index/merge_policy.rs
  pg_search/src/index/writer/index.rs
  pg_search/src/lib.rs
  pg_search/src/postgres/options.rs
  pg_search/src/postgres/storage/buffer.rs
  pg_search/src/postgres/storage/fsm.rs
  pg_search/src/postgres/storage/utils.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x

#3085 chore: clean up + test null subselects
  pg_search/src/postgres/customscan/pdbscan/solve_expr.rs
  pg_search/tests/pg_regress/expected/custom_scan_with_subquery.out
  pg_search/tests/pg_regress/sql/custom_scan_with_subquery.sql
Labels: cherry-pick/0.18.x

#3092 fix: fix failing test
  pg_search/src/index/writer/index.rs
Labels: cherry-pick/0.17.x, cherry-pick/0.18.x
